//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\b1025118\OneDrive - Bombardier\Documents\NXOPEN Codes\BANxOpen.Ui.SheetMetalBead\src\BLOCKUI_BEAD.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: b1025118
//              Version: Designcenter 2606
//              Date: 09-22-2026  (Format: mm-dd-yyyy)
//              Time: 15:30 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;

// >>> HAND-EDITED — re-add after any Styler regeneration, per Skills/with-block-ui.md §1/§4 <<<
// The Styler emits this file into the global namespace. Declaring the namespace keeps it with the
// rest of the assembly (BeadCommand, BlockAccessor, BeadDialogPresenter), and means the
// Presenter property below can name the type directly instead of fully qualifying it.
namespace BANxOpen.Ui.SheetMetal.Bead;
// >>> END HAND-EDITED <<<

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class BLOCKUI_BEAD
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.Group group0;
    private NXOpen.BlockStyler.SuperSection super_section0;// Block type: Super Section
    private NXOpen.BlockStyler.SelectObject selection0;// Block type: Selection
    private NXOpen.BlockStyler.Button btn_ClearAll;// Block type: Button
    private NXOpen.BlockStyler.ListBox list_SelectedObjects;// Block type: List Box
    private NXOpen.BlockStyler.Separator separator02;// Block type: Separator
    private NXOpen.BlockStyler.Label label_currentPref;// Block type: Label
    private NXOpen.BlockStyler.Separator separator01;// Block type: Separator
    private NXOpen.BlockStyler.TabControl tabControl;// Block type: Tabs Page
    private NXOpen.BlockStyler.Group tabPreference;
    private NXOpen.BlockStyler.Group group;// Block type: Group
    private NXOpen.BlockStyler.Enumeration enum_SmStd;// Block type: Enumeration
    private NXOpen.BlockStyler.Enumeration enum_SmMaterial;// Block type: Enumeration
    private NXOpen.BlockStyler.Button button0;// Block type: Button
    private NXOpen.BlockStyler.Tree ShtMetal;// Block type: Tree Control
    private NXOpen.BlockStyler.Group tabdBead;
    private NXOpen.BlockStyler.Group group1;// Block type: Group
    private NXOpen.BlockStyler.Enumeration enum_BABead;// Block type: Enumeration
    private NXOpen.BlockStyler.Tree BeadOptions;// Block type: Tree Control
    private NXOpen.BlockStyler.Separator separator0;// Block type: Separator
    private NXOpen.BlockStyler.DoubleBlock double_R;// Block type: Double
    private NXOpen.BlockStyler.DoubleBlock double_W;// Block type: Double
    private NXOpen.BlockStyler.DoubleBlock double_H;// Block type: Double
    private NXOpen.BlockStyler.DoubleBlock double_PRAD;// Block type: Double
    private NXOpen.BlockStyler.ReverseDirection direction0;// Block type: Reverse Direction
    private NXOpen.BlockStyler.DrawingArea BeadImage;// Block type: Drawing Area
    private NXOpen.BlockStyler.Table table;// Block type: TableLayout
    private NXOpen.BlockStyler.Toggle togglePreview;// Block type: Toggle

    // >>> HAND-EDITED — re-add after any Styler regeneration, per Skills/with-block-ui.md §1/§4 <<<
    // TheDialog is exposed so BeadCommand can hand it to BlockAccessor, which resolves blocks the same way
    // initialize_cb does. Presenter is set by BeadCommand.cs right after construction; every callback below
    // delegates into it.
    public NXOpen.BlockStyler.BlockDialog TheDialog => theDialog;
    public BeadDialogPresenter? Presenter { get; set; }
    // >>> END HAND-EDITED <<<
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesEnabled
    //------------------------------------------------------------------------------
    public static readonly int              SnapPointTypesEnabled_UserDefined = (1 << 0);
    public static readonly int                 SnapPointTypesEnabled_Inferred = (1 << 1);
    public static readonly int           SnapPointTypesEnabled_ScreenPosition = (1 << 2);
    public static readonly int                 SnapPointTypesEnabled_EndPoint = (1 << 3);
    public static readonly int                 SnapPointTypesEnabled_MidPoint = (1 << 4);
    public static readonly int             SnapPointTypesEnabled_ControlPoint = (1 << 5);
    public static readonly int             SnapPointTypesEnabled_Intersection = (1 << 6);
    public static readonly int                SnapPointTypesEnabled_ArcCenter = (1 << 7);
    public static readonly int            SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
    public static readonly int            SnapPointTypesEnabled_ExistingPoint = (1 << 9);
    public static readonly int             SnapPointTypesEnabled_PointonCurve = (1 <<10);
    public static readonly int           SnapPointTypesEnabled_PointonSurface = (1 <<11);
    public static readonly int         SnapPointTypesEnabled_PointConstructor = (1 <<12);
    public static readonly int     SnapPointTypesEnabled_TwocurveIntersection = (1 <<13);
    public static readonly int             SnapPointTypesEnabled_TangentPoint = (1 <<14);
    public static readonly int                    SnapPointTypesEnabled_Poles = (1 <<15);
    public static readonly int         SnapPointTypesEnabled_BoundedGridPoint = (1 <<16);
    public static readonly int         SnapPointTypesEnabled_FacetVertexPoint = (1 <<17);
    public static readonly int            SnapPointTypesEnabled_DefiningPoint = (1 <<18);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int             SnapPointTypesOnByDefault_EndPoint = (1 << 3);
    public static readonly int             SnapPointTypesOnByDefault_MidPoint = (1 << 4);
    public static readonly int         SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
    public static readonly int         SnapPointTypesOnByDefault_Intersection = (1 << 6);
    public static readonly int            SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
    public static readonly int        SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
    public static readonly int        SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
    public static readonly int         SnapPointTypesOnByDefault_PointonCurve = (1 <<10);
    public static readonly int       SnapPointTypesOnByDefault_PointonSurface = (1 <<11);
    public static readonly int     SnapPointTypesOnByDefault_PointConstructor = (1 <<12);
    public static readonly int     SnapPointTypesOnByDefault_BoundedGridPoint = (1 <<16);
    public static readonly int     SnapPointTypesOnByDefault_FacetVertexPoint = (1 <<17);
    //------------------------------------------------------------------------------
    //Bit Option for Property: EntityType
    //------------------------------------------------------------------------------
    public static readonly int                 EntityType_AllowEdgesandCurves = (1 << 2);
    public static readonly int                         EntityType_AllowPoints = (1 << 3);
    //------------------------------------------------------------------------------
    //Bit Option for Property: CurveRules
    //------------------------------------------------------------------------------
    public static readonly int                         CurveRules_SingleCurve = (1 << 0);
    public static readonly int                     CurveRules_ConnectedCurves = (1 << 1);
    public static readonly int                       CurveRules_TangentCurves = (1 << 2);
    public static readonly int                           CurveRules_FaceEdges = (1 << 3);
    public static readonly int                          CurveRules_SheetEdges = (1 << 5);
    public static readonly int                       CurveRules_FeatureCurves = (1 << 6);
    public static readonly int                         CurveRules_InferCurves = (1 << 7);
    public static readonly int                CurveRules_RegionBoundaryCurves = (1 <<11);
    public static readonly int                       CurveRules_CurvesinGroup = (1 <<12);
    public static readonly int                   CurveRules_OuterEdgesofFaces = (1 <<13);
    public static readonly int                     CurveRules_RibTopFaceEdges = (1 <<14);
    public static readonly int            CurveRules_FeatureIntersectionEdges = (1 <<15);
    public static readonly int              CurveRules_GroupFaceBoundaryEdges = (1 <<16);
    
    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public BLOCKUI_BEAD()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "BLOCKUI_BEAD.dlx";
            theDialog = theUI.CreateDialog(theDlxFileName);
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddCancelHandler(new NXOpen.BlockStyler.BlockDialog.Cancel(cancel_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        // >>> HAND-EDITED — re-add after any Styler regeneration <<<
        // The Styler generates `catch (Exception ex) { throw ex; }`, which resets the stack trace to this line
        // and loses where the failure actually came from.
        catch (Exception)
        {
            //---- Enter your exception handling code here -----
            throw;
        }
        // >>> END HAND-EDITED <<<
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Remove the following conditional definitions:
    //
    //                a) #if USER_EXIT
    //                    #endif//USER_EXIT
    //        2) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        3) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //    3. THROUGH CALLBACK OF ANOTHER DIALOG
    //
    //        1) Remove the following conditional definition:
    //             #if CALLBACK
    //             #endif//CALLBACK
    //        2) Call the following line of code from where ever you want to lauch this dialog.
    //             BLOCKUI_BEAD.Show_BLOCKUI_BEAD();
    //        3) Integrate this file with your main application file.
    //
    //------------------------------------------------------------------------------
#if USER_EXIT
    public static void Main()
    {
        BLOCKUI_BEAD theBLOCKUI_BEAD = null;
        try
        {
            theBLOCKUI_BEAD = new BLOCKUI_BEAD();
            // The following method shows the dialog immediately
            theBLOCKUI_BEAD.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if(theBLOCKUI_BEAD != null)
                theBLOCKUI_BEAD.Dispose();
                theBLOCKUI_BEAD = null;
        }
    }
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
     public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
         return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
#endif//USER_EXIT
    
    //------------------------------------------------------------------------------
    //This method launches the dialog to screen
    //------------------------------------------------------------------------------
    public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
    {
        NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;
        try
        {
            dialogResponse = theDialog.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return dialogResponse;
    }
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }
    
#if CALLBACK
    //------------------------------------------------------------------------------
    //Method name: Show_BLOCKUI_BEAD
    //------------------------------------------------------------------------------
    public static void Show_BLOCKUI_BEAD()
    {
        BLOCKUI_BEAD theBLOCKUI_BEAD = null;
        try
        {
            theBLOCKUI_BEAD = new BLOCKUI_BEAD();
            // The following method shows the dialog immediately
            theBLOCKUI_BEAD.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            theBLOCKUI_BEAD.Dispose();
            theBLOCKUI_BEAD = null;
        }
    }
#endif//CALLBACK
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group0 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group0");
            super_section0 = (NXOpen.BlockStyler.SuperSection)theDialog.TopBlock.FindBlock("super_section0");
            selection0 = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("selection0");
            btn_ClearAll = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("btn_ClearAll");
            list_SelectedObjects = (NXOpen.BlockStyler.ListBox)theDialog.TopBlock.FindBlock("list_SelectedObjects");
            separator02 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator02");
            label_currentPref = (NXOpen.BlockStyler.Label)theDialog.TopBlock.FindBlock("label_currentPref");
            separator01 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator01");
            tabControl = (NXOpen.BlockStyler.TabControl)theDialog.TopBlock.FindBlock("tabControl");
            tabPreference = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("tabPreference");
            group = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group");
            enum_SmStd = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum_SmStd");
            enum_SmMaterial = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum_SmMaterial");
            button0 = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button0");
            ShtMetal = (NXOpen.BlockStyler.Tree)theDialog.TopBlock.FindBlock("ShtMetal");
            tabdBead = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("tabdBead");
            group1 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group1");
            enum_BABead = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum_BABead");
            BeadOptions = (NXOpen.BlockStyler.Tree)theDialog.TopBlock.FindBlock("BeadOptions");
            separator0 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator0");
            double_R = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("double_R");
            double_W = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("double_W");
            double_H = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("double_H");
            double_PRAD = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("double_PRAD");
            direction0 = (NXOpen.BlockStyler.ReverseDirection)theDialog.TopBlock.FindBlock("direction0");
            BeadImage = (NXOpen.BlockStyler.DrawingArea)theDialog.TopBlock.FindBlock("BeadImage");
            table = (NXOpen.BlockStyler.Table)theDialog.TopBlock.FindBlock("table");
            togglePreview = (NXOpen.BlockStyler.Toggle)theDialog.TopBlock.FindBlock("togglePreview");
            //------------------------------------------------------------------------------
            //Registration of Treelist specific callbacks
            //------------------------------------------------------------------------------
            //ShtMetal.SetOnExpandHandler(new NXOpen.BlockStyler.Tree.OnExpandCallback(OnExpandCallback));
            
            //ShtMetal.SetOnInsertColumnHandler(new NXOpen.BlockStyler.Tree.OnInsertColumnCallback(OnInsertColumnCallback));
            
            //ShtMetal.SetOnInsertNodeHandler(new NXOpen.BlockStyler.Tree.OnInsertNodeCallback(OnInsertNodecallback));
            
            //ShtMetal.SetOnDeleteNodeHandler(new NXOpen.BlockStyler.Tree.OnDeleteNodeCallback(OnDeleteNodecallback));
            
            //ShtMetal.SetOnPreSelectHandler(new NXOpen.BlockStyler.Tree.OnPreSelectCallback(OnPreSelectcallback));
            
            //ShtMetal.SetOnSelectHandler(new NXOpen.BlockStyler.Tree.OnSelectCallback(OnSelectcallback));
            
            //ShtMetal.SetOnStateChangeHandler(new NXOpen.BlockStyler.Tree.OnStateChangeCallback(OnStateChangecallback));
            
            //ShtMetal.SetToolTipTextHandler(new NXOpen.BlockStyler.Tree.ToolTipTextCallback(ToolTipTextcallback));
            
            //ShtMetal.SetColumnSortHandler(new NXOpen.BlockStyler.Tree.ColumnSortCallback(ColumnSortcallback));
            
            //ShtMetal.SetStateIconNameHandler(new NXOpen.BlockStyler.Tree.StateIconNameCallback(StateIconNameCallback));
            
            //ShtMetal.SetOnBeginLabelEditHandler(new NXOpen.BlockStyler.Tree.OnBeginLabelEditCallback(OnBeginLabelEditCallback));
            
            //ShtMetal.SetOnEndLabelEditHandler(new NXOpen.BlockStyler.Tree.OnEndLabelEditCallback(OnEndLabelEditCallback));
            
            //ShtMetal.SetOnEditOptionSelectedHandler(new NXOpen.BlockStyler.Tree.OnEditOptionSelectedCallback(OnEditOptionSelectedCallback));
            
            //ShtMetal.SetAskEditControlHandler(new NXOpen.BlockStyler.Tree.AskEditControlCallback(AskEditControlCallback));
            
            //ShtMetal.SetOnMenuHandler(new NXOpen.BlockStyler.Tree.OnMenuCallback(OnMenuCallback));;
            
            //ShtMetal.SetOnMenuSelectionHandler(new NXOpen.BlockStyler.Tree.OnMenuSelectionCallback(OnMenuSelectionCallback));;
            
            //ShtMetal.SetIsDropAllowedHandler(new NXOpen.BlockStyler.Tree.IsDropAllowedCallback(IsDropAllowedCallback));;
            
            //ShtMetal.SetIsDragAllowedHandler(new NXOpen.BlockStyler.Tree.IsDragAllowedCallback(IsDragAllowedCallback));;
            
            //ShtMetal.SetOnDropHandler(new NXOpen.BlockStyler.Tree.OnDropCallback(OnDropCallback));;
            
            //ShtMetal.SetOnDropMenuHandler(new NXOpen.BlockStyler.Tree.OnDropMenuCallback(OnDropMenuCallback));
            
            //ShtMetal.SetOnDefaultActionHandler(new NXOpen.BlockStyler.Tree.OnDefaultActionCallback(OnDefaultActionCallback));
            
            //BeadOptions.SetOnExpandHandler(new NXOpen.BlockStyler.Tree.OnExpandCallback(OnExpandCallback));
            
            //BeadOptions.SetOnInsertColumnHandler(new NXOpen.BlockStyler.Tree.OnInsertColumnCallback(OnInsertColumnCallback));
            
            //BeadOptions.SetOnInsertNodeHandler(new NXOpen.BlockStyler.Tree.OnInsertNodeCallback(OnInsertNodecallback));
            
            //BeadOptions.SetOnDeleteNodeHandler(new NXOpen.BlockStyler.Tree.OnDeleteNodeCallback(OnDeleteNodecallback));
            
            //BeadOptions.SetOnPreSelectHandler(new NXOpen.BlockStyler.Tree.OnPreSelectCallback(OnPreSelectcallback));
            
            //BeadOptions.SetOnSelectHandler(new NXOpen.BlockStyler.Tree.OnSelectCallback(OnSelectcallback));
            
            //BeadOptions.SetOnStateChangeHandler(new NXOpen.BlockStyler.Tree.OnStateChangeCallback(OnStateChangecallback));
            
            //BeadOptions.SetToolTipTextHandler(new NXOpen.BlockStyler.Tree.ToolTipTextCallback(ToolTipTextcallback));
            
            //BeadOptions.SetColumnSortHandler(new NXOpen.BlockStyler.Tree.ColumnSortCallback(ColumnSortcallback));
            
            //BeadOptions.SetStateIconNameHandler(new NXOpen.BlockStyler.Tree.StateIconNameCallback(StateIconNameCallback));
            
            //BeadOptions.SetOnBeginLabelEditHandler(new NXOpen.BlockStyler.Tree.OnBeginLabelEditCallback(OnBeginLabelEditCallback));
            
            //BeadOptions.SetOnEndLabelEditHandler(new NXOpen.BlockStyler.Tree.OnEndLabelEditCallback(OnEndLabelEditCallback));
            
            //BeadOptions.SetOnEditOptionSelectedHandler(new NXOpen.BlockStyler.Tree.OnEditOptionSelectedCallback(OnEditOptionSelectedCallback));
            
            //BeadOptions.SetAskEditControlHandler(new NXOpen.BlockStyler.Tree.AskEditControlCallback(AskEditControlCallback));
            
            //BeadOptions.SetOnMenuHandler(new NXOpen.BlockStyler.Tree.OnMenuCallback(OnMenuCallback));;
            
            //BeadOptions.SetOnMenuSelectionHandler(new NXOpen.BlockStyler.Tree.OnMenuSelectionCallback(OnMenuSelectionCallback));;
            
            //BeadOptions.SetIsDropAllowedHandler(new NXOpen.BlockStyler.Tree.IsDropAllowedCallback(IsDropAllowedCallback));;
            
            //BeadOptions.SetIsDragAllowedHandler(new NXOpen.BlockStyler.Tree.IsDragAllowedCallback(IsDragAllowedCallback));;
            
            //BeadOptions.SetOnDropHandler(new NXOpen.BlockStyler.Tree.OnDropCallback(OnDropCallback));;
            
            //BeadOptions.SetOnDropMenuHandler(new NXOpen.BlockStyler.Tree.OnDropMenuCallback(OnDropMenuCallback));
            
            //BeadOptions.SetOnDefaultActionHandler(new NXOpen.BlockStyler.Tree.OnDefaultActionCallback(OnDefaultActionCallback));
            
            //------------------------------------------------------------------------------
            //------------------------------------------------------------------------------
            //Registration of ListBox specific callbacks
            //------------------------------------------------------------------------------
            //list_SelectedObjects.SetAddHandler(new NXOpen.BlockStyler.ListBox.AddCallback(AddCallback));
            
            //list_SelectedObjects.SetDeleteHandler(new NXOpen.BlockStyler.ListBox.DeleteCallback(DeleteCallback));

            //------------------------------------------------------------------------------

            // >>> HAND-EDITED — re-add after any Styler regeneration <<<
            // Tree and ListBox handlers are registered by BlockAccessor (from Presenter.Initialize), not above.
            Presenter?.Initialize();
            // >>> END HAND-EDITED <<<
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
            // >>> HAND-EDITED — re-add after any Styler regeneration <<<
            // The first render fills both trees, and NX only accepts tree columns from here on.
            Presenter?.OnDialogShown();
            // >>> END HAND-EDITED <<<
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            // >>> HAND-EDITED — re-add after any Styler regeneration <<<
            errorCode = Presenter?.OnApply() ?? 1;
            // >>> END HAND-EDITED <<<
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb( NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            // >>> HAND-EDITED — re-add after any Styler regeneration. update_cb dispatches by block
            // reference (this NX version's own generated shape), so each branch calls a distinct
            // Presenter method directly rather than a string-keyed OnUpdate(name). super_section0 and selection0
            // both feed the same selection.
            // The empty branches are left exactly as generated so the next regeneration diffs cleanly; those
            // blocks have no behaviour. button0 ("Update Sheet Metal Preferences") is deliberately among them:
            // the preference follows the ShtMetal row selection, and Apply is the only thing that commits it.
            // The trees are absent on purpose — tree events never reach update_cb, they are registered on the
            // Tree itself in BlockAccessor, as is the selection list's delete. <<<
            if(block == super_section0)
            {
                // The curve selection (curves, sketch-on-the-fly); selection0 is the Bead feature selection.
                Presenter?.OnCurveSelectionChanged();
            }
            else if(block == selection0)
            {
                Presenter?.OnSelectionChanged();
            }
            else if(block == btn_ClearAll)
            {
                Presenter?.OnClearAllClicked();
            }
            else if(block == list_SelectedObjects)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator02)
            {
            //---------Enter your code here-----------
            }
            else if(block == label_currentPref)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator01)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum_SmStd)
            {
                Presenter?.OnStandardChanged();
            }
            else if(block == enum_SmMaterial)
            {
                Presenter?.OnMaterialFilterChanged();
            }
            else if(block == button0)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum_BABead)
            {
                Presenter?.OnBeadSpecChanged();
            }
            else if(block == direction0)
            {
                Presenter?.OnDirectionFlipped();
            }
            else if(block == togglePreview)
            {
                Presenter?.OnPreviewToggled();
            }
            else if(Presenter?.IsShowAllToggle(block) == true)
            {
                // Matched through BlockAccessor by block ID, so this works whether or not the Styler has
                // generated a field for the Show All toggle yet.
                Presenter.OnShowAllToggled();
            }
            // >>> END HAND-EDITED <<<
            else if(block == separator0)
            {
            //---------Enter your code here-----------
            }
            else if(block == double_R)
            {
            //---------Enter your code here-----------
            }
            else if(block == double_W)
            {
            //---------Enter your code here-----------
            }
            else if(block == double_H)
            {
            //---------Enter your code here-----------
            }
            else if(block == double_PRAD)
            {
            //---------Enter your code here-----------
            }
            else if(block == BeadImage)
            {
            //---------Enter your code here-----------
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            errorCode = apply_cb();
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: cancel_cb
    //------------------------------------------------------------------------------
    public int cancel_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    //------------------------------------------------------------------------------
    //Treelist specific callbacks
    //------------------------------------------------------------------------------
    //public void OnExpandCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
    //{
    //}
    
    //public void OnInsertColumnCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}
    
    //public void OnInsertNodecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
    //{
    //}
    
    //public void OnDeleteNodecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
    //{
    //}
    
    //public void OnPreSelectcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, bool Selected)
    //{
    //}
    
    //public void OnSelectcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, bool Selected)
    //{
    //}
    
    //public void OnStateChangecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int State)
    //{
    //}
    
    //public string ToolTipTextcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}
    
    //public int ColumnSortcallback(NXOpen.BlockStyler.Tree tree, int columnID, NXOpen.BlockStyler.Node node1, NXOpen.BlockStyler.Node node2)
    //{
    //}
    
    //public string StateIconNameCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int state)
    //{
    //}
    
    //public Tree.BeginLabelEditState OnBeginLabelEditCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}
    
    //public Tree.EndLabelEditState OnEndLabelEditCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, string editedText)
    //{
    //}
    
    //public Tree.EditControlOption OnEditOptionSelectedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, int selectedOptionID, string selectedOptionText, Tree.ControlType type)
    //{
    //}
    
    //public Tree.ControlType AskEditControlCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}
    
    //public void OnMenuCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}
    
    //public void OnMenuSelectionCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int menuItemID)
    //{
    //}
    
    //public Node.DropType IsDropAllowedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID)
    //{
    //}
    
    //public Node.DragType IsDragAllowedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}
    
    //public bool OnDropCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node[] node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID, Node.DropType dropType, int dropMenuItemId)
    //{
    //}
    
    //public void OnDropMenuCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID)
    //{
    //}
    
    //public void OnDefaultActionCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}
    
    //------------------------------------------------------------------------------
    //ListBox specific callbacks
    //------------------------------------------------------------------------------
    //public int  AddCallback (NXOpen.BlockStyler.ListBox list_box)
    //{
    //}
    
    //public int  DeleteCallback(NXOpen.BlockStyler.ListBox list_box)
    //{
    //}
    
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist =null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }
    
}
